[project]
name = "dagster_questdb_boilerplate"
version = "0.1.0"
description = "Dagster + QuestDB starter boilerplate"
readme = "README.md"
authors = [
    { name = "Marius Kraft", email = "kraft.marius@proton.me" }
]
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.13.20",
    "httpx2>=2.12.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.5",
    "questdb>=5.0.0",
]

[project.scripts]
dagster-questdb-boilerplate = "dagster_questdb_boilerplate:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "dagster-dg-cli>=1.13.20",
    "dagster-webserver>=1.13.20",
    "ruff>=0.16.5",
    "ty>=0.0.75",
]

[tool.ruff]
target-version = "py313"
line-length = 100
src = ["src", "tests"]

[tool.ruff.lint.isort]
known-first-party = ["dagster_questdb_boilerplate"]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "dagster_questdb_boilerplate"
registry_modules = [
    "dagster_questdb_boilerplate.components.*",
]


