networks:
  default:

services:
  questdb:
    image: questdb/questdb:10.0.1
    container_name: ${COMPOSE_PROJECT_NAME}_questdb
    restart: no
    environment:
      - QDB_TELEMETRY_ENABLED
      - QDB_PG_USER
      - QDB_PG_PASSWORD
      - QDB_PG_READONLY_USER_ENABLED
      - QDB_PG_READONLY_USER
      - QDB_PG_READONLY_PASSWORD
    ports:
      - "${QDB_PORT}:9000" # REST API & Web Console
    networks:
      - default
    volumes:
      - questdb_data:/var/lib/questdb
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -v http://127.0.0.1:9003",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  questdb_data:
    driver: local
